stages:
  - mirror

before_script:
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )"
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git config --global user.email "bitbucketuser@spry.com"
  - git config --global user.name "SPRY BitBucket User"
  - ssh -T git@bitbucket.org

mirror:
  stage: mirror
  script:
    - git push --mirror git@bitbucket.org:sprymobile/spry-mobile.git
