# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'spryproject' do
  pod 'AppCenter/Crashes', '~> 1.10.0'
  pod 'AppCenter/Analytics', '~> 1.10.0'
  pod 'AppCenterReactNativeShared', '~> 1.9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  rn_maps_path = '../node_modules/react-native-maps'
  # Pods for spryproject

  platform :ios, '9.0'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'jschelpers',
    'cxxreact',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTWebSocket',
  ]
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-torch', :path => '../node_modules/react-native-torch'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end
